name: Test Manual Run3
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Client version'
        required: true
        default: 'latest'

jobs:
  publish-network-client:
    runs-on: ["self-hosted", "ubuntu-22.04"]
    container:
        image: ubuntu:latest
        options: --rm
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: echo
        run: |
          echo "Test 3 from other branch"
