name: Release
on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:
    inputs:
      live-run:
        type: boolean
        description: Live-run
        required: false
      version:
        type: string
        description: Release number
        required: true
      branch:
        type: string
        description: Release branch
        required: false


jobs:
  release-library:
    runs-on: ["ubuntu-22.04"]
    container:
        image: ubuntu:latest
        options: --rm
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Bump and tag project
        run: bash ci/scripts/bump-and-tag.bash
        env:
          VERSION: ${{ inputs.version }}
          LIVE_RUN: ${{ inputs.live_run }}
          BUMP_DEPS_BRANCH: ${{ inputs.zenoh-version && format('release/{0}', inputs.zenoh-version) || '' }}
          GIT_USER_NAME: eclipse-zenoh-bot
          GIT_USER_EMAIL: eclipse-zenoh-bot@users.noreply.github.com

      - name: echo
        run: |
          echo "Test"
          echo ${{ steps.create-release-branch.outputs.version }}
          echo ${{ inputs.zenoh-version }}
          echo ${{ inputs.zenoh-version && 'zenoh.*' || '' }}
          echo ${{ inputs.zenoh-version && format('release/{0}', inputs.zenoh-version) || '' }}
