name: Release ts_project

on:
  # push:
  #   tags:
  #     - '[0-9]+.*'
  workflow_dispatch:
    inputs:
    live-run:
      type: boolean
      description: Live-run
      required: false
    version:
      type: string
      description: Release number
      required: true
    branch:
      type: string
      description: Release branch
      required: false

defaults:
  run:
    shell: bash

jobs:
  package:
    name: Publish Typescript Project
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump and tag project
        run: bash ci/scripts/bump-and-tag.bash
        env:
          LIVE_RUN: ${{ inputs.live_run }}
          VERSION: ${{ inputs.version }}
          GIT_USER_NAME: charles-schleich-bot
          GIT_USER_EMAIL: charles-schleich-bot@users.noreply.github.com

      - name: git config
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: ./ts_project

      - name: Transpile Code
        with: 
          dir: ./ts_project
        run: yarn run build

      - name: Publish
        id: publish
        shell: bash
        env:
          YARN_NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: |
          npm install
          npx release-it

      - name: Cleanup
        if: always()
        run: |
          rm -rf node_modules
          rm -rf dist
          rm -rf package-lock.json
