name: Release
on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:
    inputs:
      live-run:
        type: boolean
        description: Live-run
        required: false
      version:
        type: string
        description: Release number
        required: true
      branch:
        type: string
        description: Release branch
        required: false


jobs:
  release-library:
    runs-on: ubuntu-latest
    steps:
      # - id: create-release-branch
      #   uses: eclipse-zenoh/ci/create-release-branch@main
      #   with:
      #     repo: ${{ github.repository }}
      #     live-run: ${{ inputs.live-run || false }}
      #     version: ${{ inputs.version }}
      #     branch: ${{ inputs.branch }}
      #     github-token: ${{ secrets.BOT_TOKEN_WORKFLOW }}


      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Bump and tag project
        run: bash ci/scripts/bump-and-tag.bash
        env:
          LIVE_RUN: ${{ inputs.live_run }}
          VERSION: ${{ inputs.version }}
          GIT_USER_NAME: charles-schleich-bot
          GIT_USER_EMAIL: charles-schleich-bot@users.noreply.github.com

      - name: echo
        run: |
          echo "Test"
          echo ${{ steps.create-release-branch.outputs.version }}
          echo ${{ inputs.live-run }}
          echo ${{ inputs.version && 'zenoh.*' || '' }}
          echo ${{ inputs.branch && format('release/{0}', inputs.zenoh-version) || '' }}
